"""Recording a flywheel run, and replaying it offline.

A recording is a directory that captures everything a run consumed from the outside world:

    feedback.jsonl        every human judgement, in order, with its selection propensity
    extra_answers.jsonl.gz  Jev answers collected beyond the bundled fixtures (the answers to
                          elements the analyst proposed)
    script.json           the ordered steps that happened between labels: each refit, and
                          each steering round with the analyst's exact reply and the human's
                          decision
    README.md             who or what produced the labels, said plainly

Replaying feeds the labels back in order and runs the recorded steps against a fresh
workspace. Nothing on the network is touched: the Jev answers come from the recording, the
analyst's reply is the recorded one, and the human's approvals are the recorded decisions.
Because fitting is deterministic, a replay reproduces the same scorecard lineage, which is
what lets the README's chart be regenerated by anyone, with no keys, in seconds.

That is also the on-ramp: point ``flywheel record`` at your own session and you can hand
someone a directory that reproduces your result.
"""
from __future__ import annotations

import gzip
import json
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from jev_flywheel.answers import AnswerCache, import_answers_jsonl
from jev_flywheel.items import FeedbackItem, JsonlStore
from jev_flywheel.loop import refit
from jev_flywheel.scorecard import Scorecard
from jev_flywheel.workspace import Workspace

FORMAT = 1
# The engine whose answers a recording's extra_answers hold. Restoring them into a workspace for
# any other engine would put one model's answers under another's name.
RECORDED_ENGINE = "jev"
# Only these outcomes leave a trace worth replaying. A round that stopped at its price, or
# failed to reach Jev, changed nothing and depended on the network.
REPLAYABLE_DECISIONS = {"promoted", "rejected_by_human", "rejected_by_metrics",
                        "no_change_proposed", "invalid_proposal"}


class RecordingError(RuntimeError):
    pass


def _extra_answer_rows(workspace: Workspace, fixtures: Path):
    """Answers in the workspace that the bundled fixtures do not already provide."""
    baseline = AnswerCache()
    reference = Scorecard.from_yaml(
        (Path(fixtures) / "scorecards" / "reference_full.yaml").read_text())
    import_answers_jsonl(Path(fixtures) / "answers.jsonl.gz", reference.questions(), baseline)
    known = {(i, n, h) for i, n, h, _ in baseline.rows()}
    for item_id, name, qhash, answer in workspace.cache.rows():
        if (item_id, name, qhash) not in known:
            yield {"item_id": item_id, "name": name, "qhash": qhash,
                   "model": workspace.cache.model, "answer": answer}


def record(workspace: Workspace, score_name: str, out: Path, fixtures: Path, *,
           title: str, provenance: str) -> Path:
    """Write a recording of the workspace's session to ``out``."""
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    feedback = workspace.feedback()
    JsonlStore(out / "feedback.jsonl", FeedbackItem).append_all(feedback)

    with gzip.open(out / "extra_answers.jsonl.gz", "wt", encoding="utf-8") as handle:
        for row in _extra_answer_rows(workspace, fixtures):
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")

    steps: List[Dict[str, Any]] = []
    events = sorted(
        (e for e in workspace.events() if e.get("score_name") == score_name
         and e["kind"] in ("fit", "rethink")), key=lambda e: e["at"])
    for event in events:
        if event["kind"] == "fit":
            steps.append({"after_labels": event["n_labeled"], "op": "refit"})
        elif event.get("decision") in REPLAYABLE_DECISIONS and event.get("analyst_reply"):
            steps.append({
                "after_labels": event["n_labeled"], "op": "steer",
                "analyst_reply": event["analyst_reply"], "model": event.get("model"),
                "approve": event["decision"] == "promoted",
                "recorded_decision": event["decision"]})
    (out / "script.json").write_text(json.dumps({
        "format": FORMAT, "title": title, "score": score_name,
        "n_labels": workspace.n_labeled(score_name), "steps": steps,
    }, indent=2, ensure_ascii=False))
    (out / "README.md").write_text(
        f"# {title}\n\n{provenance}\n\n"
        f"{workspace.n_labeled(score_name)} labels, {len(steps)} recorded steps. Replay with:\n\n"
        f"    flywheel replay {out}\n")
    return out


def load(directory: Path) -> Dict[str, Any]:
    path = Path(directory) / "script.json"
    if not path.exists():
        raise RecordingError(f"{directory} is not a recording: no script.json")
    script = json.loads(path.read_text())
    if script.get("format") != FORMAT:
        raise RecordingError(f"unsupported recording format {script.get('format')!r}")
    return script


def replay(
    directory: Path, workspace_dir: Path, fixtures: Path, *,
    on_step: Optional[Callable[[str], None]] = None,
    answers: str = "answers.jsonl.gz", engine: str = "jev",
    client_factory: Optional[Callable[[], Any]] = None,
) -> Workspace:
    """Rebuild the recorded session in a fresh workspace, offline.

    Labels are fed back in their original order, and each recorded step runs when the
    label count it followed is reached. The steering steps use the recorded analyst
    reply and the recorded human decision, so no model and no person is consulted.

    Replaying against a *different engine* keeps the labels, the refit points and the analyst's
    recorded proposal, and changes only who answers the questions: pass that engine's
    ``answers`` extract, its ``engine`` name and a ``client_factory``. The recording's extra
    answers were the recording engine's, so they are not restored -- the new engine answers the
    proposed elements itself, which is what makes the comparison a comparison.
    """
    from jev_flywheel.steer import ScriptedApprover, run_steering

    directory = Path(directory)
    script = load(directory)
    say = on_step or (lambda message: None)
    score_name = script["score"]
    workspace = Workspace.init(workspace_dir, fixtures, force=True, answers=answers, engine=engine)

    extra = directory / "extra_answers.jsonl.gz"
    if extra.exists() and engine == RECORDED_ENGINE:
        with gzip.open(extra, "rt", encoding="utf-8") as handle:
            for line in handle:
                row = json.loads(line)
                workspace.cache.put_hashed(
                    row["item_id"], row["name"], row["qhash"], row["answer"], row.get("model"))

    steps = sorted(script["steps"], key=lambda s: s["after_labels"])
    cursor = 0

    def run_due():
        nonlocal cursor
        while cursor < len(steps) and steps[cursor]["after_labels"] <= workspace.n_labeled(score_name):
            step = steps[cursor]
            cursor += 1
            if step["op"] == "refit":
                outcome = refit(workspace, score_name)
                say(f"after {workspace.n_labeled(score_name)} labels: refit {outcome.status}"
                    + (f" -> v{outcome.version}" if outcome.version else ""))
            else:
                outcome = run_steering(
                    workspace, score_name, model=step.get("model") or "recorded",
                    mock_replies=[step["analyst_reply"]],
                    hitl_handler=ScriptedApprover(default=bool(step["approve"])),
                    client_factory=client_factory, allow_spend=client_factory is not None)
                say(f"after {workspace.n_labeled(score_name)} labels: steering "
                    f"{outcome.decision}"
                    + (f" -> v{outcome.detail.get('version')}" if outcome.promoted else ""))

    for record_ in JsonlStore(directory / "feedback.jsonl", FeedbackItem):
        workspace.add_feedback(record_)
        run_due()
    run_due()
    return workspace
